# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.distance <- function(sequence1, sequence2, metric, cost_sub, cost_indel) {
    .Call('_DNABarcodeCompatibility_distance', PACKAGE = 'DNABarcodeCompatibility', sequence1, sequence2, metric, cost_sub, cost_indel)
}

